sudo: required
services:
  - docker

language: python

python:
  - 3.4
  - 3.5

os:
  - linux
#  - osx

cache:
  directories:
  - $HOME/.cache/pip

before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

install:
  - pip install --upgrade pip wheel
  - pip install --upgrade setuptools
  - pip install -r requirements-ci.txt
  - pip install coveralls
  - pip install twine

script:
  - flake8 multidict tests
  - py.test --cov=multidict tests
  - python setup.py check -rm
  - if python -c "import sys; sys.exit(sys.version_info < (3,5))"; then
        python setup.py check -s;
    fi

after_success:
  - coveralls
  - ./run_docker.sh

env:
  matrix:
    # MULTIDICT_NO_EXTENSIONS environment variables
    # are considered as enabled if they are any non empty strings.
    - MULTIDICT_NO_EXTENSIONS=
    - MULTIDICT_NO_EXTENSIONS=X


matrix:
  include:
    - python: 3.5
      script: ./upload_sdist.sh
